services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=moviely
      - POSTGRES_USER=lalo
      - POSTGRES_PASSWORD=postgres2152
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=lalo@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
